### ISSUE TITLE
无法下载apk文件

### ISSUE THREAD

**Issue by a5889199** [Orange-shirt/OrangeJs#11]

**Comment by Orange-shirt** [comment]
可能是蓝奏云的问题，试试这个吧http://t.cn/A62G51Nf

**Comment by a5889199** [comment]
麻烦再发一次，忘记用安卓下载了。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;橘衫下邂逅的时光&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年5月24日(星期天) 下午3:03
收件人:&nbsp;&quot;Orange-shirt/OrangeJs&quot;<OrangeJs@noreply.github.com&gt;;
抄送:&nbsp;&quot;a5889199&quot;<289136809@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Orange-shirt/OrangeJs] 无法下载apk文件 (#11)

**Comment by Orange-shirt** [comment]
> 麻烦再发一次，忘记用安卓下载了。------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;橘衫下邂逅的时光&quot;<notifications@github.com&gt; 发送时间:&nbsp;2020年5月24日(星期天) 下午3:03 收件人:&nbsp;&quot;Orange-shirt/OrangeJs&quot;<OrangeJs@noreply.github.com&gt;; 抄送:&nbsp;&quot;a5889199&quot;<289136809@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;; 主题:&nbsp;Re: [Orange-shirt/OrangeJs] 无法下载apk文件 (#11)

http://t.cn/A62qMx6g

**Comment by hit930** [comment]
无法下载APK文件，麻烦再发一次

**Comment by mikezhuo1022** [comment]
> > 麻烦再发一次，忘记用安卓下载了。------------------ 原始邮件 ------------------ 发件人: "橘衫下邂逅的时光"<[notifications@github.com](mailto:notifications@github.com)> 发送时间: 2020年5月24日(星期天) 下午3:03 收件人: "Orange-shirt/OrangeJs"<[OrangeJs@noreply.github.com](mailto:OrangeJs@noreply.github.com)>; 抄送: "a5889199"<[289136809@qq.com](mailto:289136809@qq.com)>;"Author"<[author@noreply.github.com](mailto:author@noreply.github.com)>; 主题: Re: [Orange-shirt/OrangeJs] 无法下载apk文件 (#11)
> 
> http://t.cn/A62qMx6g

我也没找到release，链接过期了，大佬能再发一次吗
