### ISSUE TITLE
脚本不能直接复制到autojs软件运行吗

### ISSUE THREAD

**Issue by hdstar2009** [Orange-shirt/OrangeJs#12]
试了京东三个脚本都是一样提示 Type error :cannot find function rawWindow in object

**Comment by Orange-shirt** [comment]
Auto.js的版本比较繁多，可能有些版本上是不能正常运行的，日常使用建议直接下载软件使用

**Comment by XiaofengdiZhu** [comment]
4.1.1叠蛋糕正常

**Comment by hdstar2009** [comment]
换了新版的autojs软件可以了。谢谢。
