### ISSUE TITLE
自动开启无障碍服务

### ISSUE THREAD

**Issue by whiteineyes** [Orange-shirt/OrangeJs#25]
有没有办法让软件自动开启无障碍服务？
尽管应用的电量政策已经是无限制了，但是每次都要手动去开启无障碍服务。

**Comment by Mit2g** [comment]
需要授予其root权限 否则依然无法自动获取无障碍服务
每个系统的后台机制不同 仅一个电池限制可能无法保证 请以其是否在后台正常活动为准
