### ISSUE TITLE
微信发消息脚本死循环

### ISSUE THREAD

**Issue by beckball** [Orange-shirt/OrangeJs#4]
系统版本 Android 10
微信版本 7.0.10/7.0.12  均为Play store版本
脚本版本 1.1/1.12
使用7.0.10时 新旧脚本提示在寻找通讯录按钮但始终没有点击 无限循环 此时微信界面正常 除脚本停止按钮无任何遮挡
使用7.0.12时 新旧脚本提示微信没有在主界面 尝试返回 始终没有正确识别微信主界面 无限在返回和开启微信之间循环 此时微信无任何异常 微信主界面正常  除脚本停止按钮无任何遮挡

旧脚本有成功使用过 其他脚本正常可以排除js软件问题 但近期不明原因出现此情况 望排查 感谢

**Comment by Orange-shirt** [comment]
今天定位到还是微信版本的问题，之前没有注意到即使是国内版7.0.12也必须是此版本
![qq_pic_merged_1585034426957](https://user-images.githubusercontent.com/50604463/77400223-cb104180-6de5-11ea-901f-85f88c6166f5.jpg)，因此麻烦在你使用的微信中的 【我】→【设置】→【关于微信】→双击“微信 WeChat”后截图上图中的弹窗给我，我再适配吧

**Comment by beckball** [comment]
> 今天定位到还是微信版本的问题，之前没有注意到即使是国内版7.0.12也必须是此版本
> ![qq_pic_merged_1585034426957](https://user-images.githubusercontent.com/50604463/77400223-cb104180-6de5-11ea-901f-85f88c6166f5.jpg)，因此麻烦在你使用的微信中的 【我】→【设置】→【关于微信】→双击“微信 WeChat”后截图上图中的弹窗给我，我再适配吧

(![Screenshot_20200324-154747__01.jpg](https://i.loli.net/2020/03/24/AjbuGznv8H15VBp.jpg))
感谢

**Comment by Orange-shirt** [comment]
“自动微信发消息”已支持微信7.0.12Play版本了，同时也支持单个文件发送啦🎉

**Comment by beckball** [comment]
> “自动微信发消息”已支持微信7.0.12Play版本了，同时也支持单个文件发送啦🎉

似乎依然不行 依旧在主界面无法识别点击 通讯录 情况如图
![Screenshot_20200325-004508.jpg](https://i.loli.net/2020/03/25/T5kMs18LRFUZSmC.jpg)

**Comment by Orange-shirt** [comment]
![PicsArt_03-25-01 08 18](https://user-images.githubusercontent.com/50604463/77455776-4220f680-6e35-11ea-9e8a-b7d6ab9bbc76.png)
新脚本我在两台不同品牌和系统的设备上测试了此版本均没有任何问题的，所以如果你现在微信还是此版本的话你就需要排查你的其它软件了，尤其是会显示悬浮窗或监控屏幕之类的软件，例如：自动跳过广告的软件或脚本等，如果你使用的是Auto.js来运行脚本的话可以下载Orange Js（橘衫の脚本）软件来运行脚本就无需手动更新且可以排除Js软件的问题了。

**Comment by beckball** [comment]
> ![PicsArt_03-25-01 08 18](https://user-images.githubusercontent.com/50604463/77455776-4220f680-6e35-11ea-9e8a-b7d6ab9bbc76.png)
> 新脚本我在两台不同品牌和系统的设备上测试了此版本均没有任何问题的，所以如果你现在微信还是此版本的话你就需要排查你的其它软件了，尤其是会显示悬浮窗或监控屏幕之类的软件，例如：自动跳过广告的软件或脚本等，如果你使用的是Auto.js来运行脚本的话可以下载Orange Js（橘衫の脚本）软件来运行脚本就无需手动更新且可以排除Js软件的问题了。

感谢建议 测试过后发现你的apk确实可以正常使用 是autojs在运行的过程中出现一些问题 我也正在排查
Thx again
